### ISSUE TITLE
感觉有个bug

### ISSUE THREAD

**Issue by guogj** [nick-bai/snake#24]
如果showOperate 这个方法让没有权限的按钮显示，

base.php 里的 这个权限拦截不掉的，
 if(empty(authCheck($control . '/' . $action))){
            if(request()->isAjax()){
                return msg(403, '', '您没有权限');
            }
            $this->error('403 您没有权限');
        }
但是这个样可以拦截
 if(empty(authCheck($control . '/' . $action))){
            $this->error('403 您没有权限');
        }

**Comment by nick-bai** [comment]
这个和按钮的显示无关
