### ISSUE TITLE
这个权限验证是怎么感脚不是很对啊？？

### ISSUE THREAD

**Issue by hellowolrds** [nick-bai/snake#26]
如果新建一个方法，在分配权限时，没有分配，还是能使用这个功能
`function authCheck($rule)
{
    $control = explode('/', $rule)['0'];
    if(in_array($control, ['login', 'index'])){
        return true;
    }

    if(in_array($rule, cache(session('role_id')))){
        return true;
    }

    return false;
}`
这个权限校验，总感觉不对，少了什么吧

**Comment by nick-bai** [comment]
admin跳过权限校验的，有问题加群讨论
