### ISSUE TITLE
node里面有个url字段就够了，不需要什么module、control、action，反正也没用到啊

### ISSUE THREAD

**Issue by he426100** [nick-bai/snake#3]

**Comment by nick-bai** [comment]
你的意思是直接拼接成url,来通过url来判断全显示吧？我的代码有用到这些，你有你的想法可以的

**Comment by he426100** [comment]
我把表node改成这样了：`id`,`pid`,`title`,`url`,`icon`,`sort`,`is_hide`， module_name的作用我是没找到，control_name和action_name看来看去也不过是拼接成control/action， 那干脆就一个url代替了， 节点增删查改排序我都做了， 再加一个设置功能就完善了。

**Comment by nick-bai** [comment]
嗯嗯，可以这么做。我是之前的一个项目RBAC是这么做的。所以我就继续这个做了。你说的很有道理。你是不是  《基于THINKPHP5 多微信开发框架，让微信开发飞起来》,这个文章的作者？

**Comment by nick-bai** [comment]
至于节点的管理，我是觉得因为节点这个东西只能专业的人维护，写到功能里面，没那个必要。不过仁者见仁

**Comment by he426100** [comment]
不是， 我还没想好要用这个后台框架做什么东西， 只是觉得总有一天可能要用到， 反正这个足够简单， 学习也好， 改造也罢， 总是要好过从零开始

**Comment by nick-bai** [comment]
嗯嗯，你很有想法，可以自己做一个出来，我写的不是很好，也是很仓促的东西。你提出的很多都是比较不错的想法，只是我没多少时间去捣鼓这个东西。工作也忙啊，哈哈。希望你搞出一个更好的

**Comment by he426100** [comment]
嗯， 等我想明白要做什么再说吧， snake的代码我已全部看过， 有心改动的地方也全改了， 比如什么useradd通通改成add了，只是觉得个性化的东西不利于新模型的快速复制。tp5对模型和数据库这块的改动还未深入了解，从习惯出发， 去掉了model里面的snake_

**Comment by nick-bai** [comment]
用什么框架都一样，尽量少用他们的ORM，能最干脆的通过sql就通过sql来，这样可以减少解析造成的性能损失。

**Comment by liyijun0417** [comment]
进入登陆页面无限跳转呢  、

**Comment by nick-bai** [comment]
进入线上体验页面无限跳转？

**Comment by liyijun0417** [comment]
是的呢 ， @nick-bai ，部署在本地也是无限刷新登陆页 ， 线上体验地址也是的

**Comment by he426100** [comment]
@liyijun0417 好奇的问下， 你访问别的网站能登陆吗

**Comment by nick-bai** [comment]
我查看了，没问题的

**Comment by liyijun0417** [comment]
应该是前端兼容性问题 ， 刚刚用的是360安全浏览器的兼容模式就会出现无限刷新的情况 ， 切换成急速模式了就不会无限刷新了 。

**Comment by he426100** [comment]
我猜是你的IE设置拒绝cookie了， 所谓兼容模式就是IE嘛

**Comment by he426100** [comment]
https://github.com/jupeter/clean-code-php

**Comment by nick-bai** [comment]
加群讨论吧

**Comment by he426100** [comment]
哈哈， 还在啊， 还以为这个没维护了， 前端时间看到的clean-code-php， 最近在segmentfault又看到了

**Comment by nick-bai** [comment]
进群吧

**Comment by he426100** [comment]
怎么进

**Comment by nick-bai** [comment]
159640205  已经做成可以安装的了
