### ISSUE TITLE
Model里的文件名中带不带model？

### ISSUE THREAD

**Issue by he426100** [nick-bai/snake#4]
带的话肯定就不会跟control里的类名冲突了， 不带也可以在use的时候用as做别名，之所以纠结这个是想让所有命名、文件名简单化。 纠结完Model就该纠结validate了 。。

**Comment by nick-bai** [comment]
按照tp设计的思路来说没必要带，就像你说的那样会出现和controller中重名的尴尬问题，要不统一带，要不都不带，根据命名空间的别名去识别。这个看你怎么规划。要不就model起别的名字

**Comment by he426100** [comment]
试了下， validate类名不带validate后缀更方便，$this->validate() 就会自动找验证类了

**Comment by nick-bai** [comment]
小问题没必要纠结，越是在意这些花里胡哨的功能，越是损失性能，我有debug过他这个验证的，走的文件太多了，严重拖沓。

**Comment by he426100** [comment]
明白
