### ISSUE TITLE
验证码图片不显示

### ISSUE THREAD

**Issue by ZengR** [nick-bai/snake#7]
![ver](https://cloud.githubusercontent.com/assets/19203943/21451012/c44e44ac-c936-11e6-8d2f-dcf5d824a520.png)

**Comment by nick-bai** [comment]
我认为 浏览的起的 F12 是个好东西，tp5手册也是个好东西。遇到问题自己不去调试，去问别人的效率是最低的。

**Comment by ZengR** [comment]
纯php新手上路，很多不懂，不好意思。打扰到您了

**Comment by nick-bai** [comment]
这种问题别人远程没办法告诉你，自己学着去摸索

**Comment by he426100** [comment]
右键查看图片， 另存为html文件， 打开文件就看到错误了
